.eslintrc.js, .prettierrc
<br><br>
- 루트 폴더에 `eslint` 및 `prettier` 설정
=> 공통 프로젝트 개발환경 세팅

mediaServer/package-lock.json, mediaServer/package.json
<br><br>
ESLint 및 Prettier 관련 패키지 설치 및 적용
=> 미디어 서버 ESLint 및 Prettier 추가

.gitignore, mediaServer/core/rtmp/handshake.ts, mediaServer/jest.config.js, mediaServer/main.ts, mediaServer/nodemon.json, mediaServer/package-lock.json, mediaServer/package.json, mediaServer/test/core/rtmp.test.ts, mediaServer/tsconfig.json
<br><br>
RTMP Handshake 과정을 모듈로 분리
- RTMP Handshake Packet 할당
- C1 Packet 분리 할당
- RTMP Handshake Packet 전송
=> RTMP Handshake 구현

client/src/app/layout.tsx
<br><br>
- Noto_Sans_KR className을 body에 추가함
=> setting: 폰트 className설정

client/package-lock.json, client/package.json, client/public/mockServiceWorker.js, client/src/app/MswInitializer.tsx, client/src/app/components/Ping.tsx, client/src/app/layout.tsx, client/src/app/page.tsx, client/src/app/server/browser.ts, client/src/app/server/handlers.ts, client/src/app/server/init.ts, client/src/app/server/node.ts, client/tsconfig.json
<br><br>
- handler, browser 설정
- 진입점에서 worker 시작
- 서버 / 브라우저 분기처리
- API 예시 작성
=> setting: msw 설정

client/package-lock.json, client/package.json, client/src/app/__test__/sum.test.ts, client/src/app/categories/features/CategoryCard.tsx, client/src/app/categories/page.tsx, client/src/app/page.test.tsx, client/src/app/page.tsx, client/vitest.config.ts, client/vitest.setup.ts
<br><br>
- vitest 설치
- vitest.config.ts / vitest.setup.ts 설정
- 간단한 test 추가
=> setting: vitest 세팅

client/plugins/tailwind.plugin.ts, client/src/app/page.tsx, client/tailwind.config.ts
<br><br>
- 폰트 디테일하게 분류
- 폰트 plugins 추가
=> setting: 폰트 설정

client/src/app/components/layout/LoginBtn.tsx, client/src/app/components/layout/Search.tsx, client/src/app/components/layout/StudioBtn.tsx, client/src/app/components/layout/ThemeController.tsx, client/src/app/components/layout/ToolBar.tsx, client/src/app/components/svgs/MoonSvg.tsx, client/src/app/components/svgs/StudioSvg.tsx
<br><br>
- 펀치 로고 배치
- 테마 컨트롤러 배치
- 스튜디오 버튼 배치
- 로그아웃 버튼 배치
=> feature: Toolbar UI 구성

client/package-lock.json, client/package.json, client/src/app/components/layout/Header.tsx, client/src/app/components/layout/Search.tsx, client/src/app/components/layout/SearchView.tsx, client/src/app/components/svgs/DeleteSvg.tsx, client/src/app/globals.css
<br><br>
- 검색창을 구성하기 위한 컨트롤러, 뷰
=> feat: 검색창 UI

client/src/app/GlobalProvider.tsx, client/src/app/categories/page.tsx, client/src/app/components/layout/LogoutBtn.tsx, client/src/app/components/layout/ToolBar.tsx, client/src/app/hooks/useUser.ts, client/src/app/hooks/useUserContext.ts, client/src/app/layout.tsx, client/src/app/page.tsx, client/src/app/providers/UserProvider.tsx, client/tsconfig.json
<br><br>
- 로그인 여부 상태를 관리하기 위한 프로바이더 및 글로벌 프로바이더
- UserContextProvider로 래핑하는 프로바이더
- useUserContext, useUser 훅
- GlobalProvider
- 임의 데이터로 로그인/로그아웃 테스트
- SSR 테스팅 및 카테고리 페이지 title 변경 테스트
=> feat: 로그인 여부 상태를 관리하기 위한 프로바이더 및 글로벌 프로바이더

client/src/app/components/layout/DeemedLink.tsx, client/src/app/components/svgs/ReadingGlassSvg.tsx, client/src/app/libs/internalTypes.ts, client/src/app/page.tsx
<br><br>
- DeemedBtn 컴포넌트화
- name, url을 props로 받음
=> feature: DeemedBtn 구현

client/src/app/components/Button.tsx, client/src/app/components/layout/LoginBtn.tsx, client/src/app/components/layout/LogoutBtn.tsx, client/src/app/page.tsx, client/src/app/server/init.ts
=> feat: 버튼 컴포넌트

client/src/app/components/Button.tsx, client/src/app/components/layout/DeemedLink.tsx, client/src/app/components/layout/LoginBtn.tsx, client/src/app/components/layout/LogoutBtn.tsx, client/src/app/components/svgs/ReadingGlassSvg.tsx, client/src/app/libs/internalTypes.ts, client/src/app/page.tsx, client/src/app/server/init.ts
<br><br>
- 공통 컴포넌트 개발
- `Button` 컴포넌트
- `DeemedLink` 컴포넌트
=> feat: Button, DeemedLink 컴포넌트

client/src/app/components/layout/ToolBar.tsx
<br><br>
- 홈 내 anchor 태그에 title attribute를 추가했다.
=> feat: 홈 링크 태그에 title 속성 추가

client/src/app/features/Badge.tsx, client/src/app/page.tsx
<br><br>
- props로 category를 받음
=> feat: Badge 컴포넌트

client/src/app/components/AccordionButton.tsx, client/src/app/components/ClientComponentForTest.tsx, client/src/app/components/svgs/DownArrowSvg.tsx, client/src/app/page.tsx
<br><br>
- 더보기/접기 UI를 위한 아코디언 버튼 UI 구현
=> feat: AccordionButton 컴포넌트

client/src/app/__mocks__/follow.ts, client/src/app/components/cabinet/Cabinet.tsx, client/src/app/components/cabinet/CabinetContainer.tsx, client/src/app/components/cabinet/FollowList.tsx, client/src/app/libs/internalTypes.ts
<br><br>
- mock데이터를 통해 팔로우 채널의 스트리머 정보를 map으로 뿌려줬음
- 추후 title absolute로 추가 필요함
=> feat: 서랍UI 팔로잉 채널 스트리머 정보 UI 구현

client/src/app/GlobalProvider.tsx, client/src/app/components/layout/HeaderControlButton.tsx, client/src/app/components/layout/ThemeController.tsx, client/src/app/components/livesGrid/Lives.tsx, client/src/app/globals.css, client/src/app/hooks/useThemeContext.ts, client/src/app/libs/constants.ts, client/src/app/libs/internalTypes.ts, client/src/app/providers/ThemeProvider.tsx, client/tailwind.config.ts
=> feat: 테마 컨텍스트

mediaServer/core/rtmp/connect.ts, mediaServer/core/rtmp/createStream.ts, mediaServer/core/rtmp/flv.ts, mediaServer/core/rtmp/packet.ts, mediaServer/core/rtmp/publish.ts, mediaServer/core/rtmp/stream.ts, mediaServer/package-lock.json, mediaServer/package.json
<br><br>
RTMP Chunk Stream을 Chunk 단위로 분리하였고, 각 Chunk에서 분리되어 오던 Payload를 정상적으로 합쳐 하나의 Chunk로 만드는 것을 확인하였다.
=> RTMP Chunk 파싱 및 Payload 병합

client/src/app/components/cabinet/CabinetContainer.tsx, client/src/app/components/cabinet/CabinetLink.tsx, client/src/app/components/cabinet/FollowList.tsx, client/src/app/components/svgs/CategorySvg.tsx
<br><br>
- 데스크톱 뷰에서 카테고리, 팔로잉 아이콘 크기 축소
- 데스크톱 뷰에서 카테고리, 팔로잉 네임 사이즈 축소
- 팔로잉 버튼 inline-flex -> flex
=> feature: 서랍 상단 UI 크기 조정 

client/src/app/__mocks__/follow.ts, client/src/app/components/cabinet/Cabinet.tsx, client/src/app/components/cabinet/CabinetContainer.tsx, client/src/app/components/cabinet/FollowList.tsx, client/src/app/components/svgs/UpArrowSvg.tsx, client/src/app/following/page.tsx, client/src/app/hooks/useDesktop.ts, client/src/app/libs/internalTypes.ts
<br><br>
- useDesktop 커스텀 훅으로 분리
- hover 시 title이 보이도록 구성
- desktop view에서 팔로잉 채널을 invisible하게 할 수 있음
- desktop view에서 accordion button으로 5개이상으로 만들 수 있음
- 온라인 상태 구분(desktop view는 개선 필요)
=> feat: 팔로잉 채널 UI 구현

client/src/app/components/cabinet/FollowList.tsx
<br><br>
- hover 단위를 group에서 peer로 변경 
- desktop hover시 background 색상 변경
=> feat: 팔로잉 채널 UI

client/src/app/components/cabinet/FollowList.tsx
<br><br>
- 서랍 UI가 닫혀있음에도 클릭되는 이벤트를 수정
=> refactor: 서랍 UI title opacity0 -> display 변경 방식으로 변경

client/plugins/tailwind.plugin.ts, client/src/app/__mocks__/lives.ts, client/src/app/components/livesGrid/LiveBadge.tsx, client/src/app/features/Badge.tsx, client/src/app/features/live/Live.tsx, client/src/app/features/live/LiveSection.tsx, client/src/app/libs/formats.ts, client/src/app/providers/LiveProvider.tsx
=> feat: live section live info 컴포넌트 UI

client/src/app/features/live/Live.tsx, client/src/app/features/live/LiveSection.tsx
<br><br>
- video, videoControllersWrapper peer로 지정
- 방송 정보 UI 작성
=> feat: 시청 페이지 UI

mediaServer/core/rtmp/flv.ts, mediaServer/core/rtmp/packet.ts, mediaServer/core/rtmp/utils.ts, mediaServer/package-lock.json, mediaServer/package.json
<br><br>
- feat: RTMP Chunk를 파싱해 분리된 비디오와 오디오 데이터를 HLS로 만들기 위해 FLV 파일로 결합하여 인코딩하였다.
- fix: RTMP Chunk 파싱 과정에서 헤더가 분리되는 상황에 대한 문제를 해결하였다.
=> 미디어 서버 비디오 및 오디오 결합

client/plugins/tailwind.plugin.ts, client/src/app/__mocks__/lives.ts, client/src/app/components/svgs/HeartFullSvg.tsx, client/src/app/components/svgs/HeartSvg.tsx, client/src/app/components/svgs/PauseSvg.tsx, client/src/app/components/svgs/PlaySvg.tsx, client/src/app/components/svgs/SoundHighSvg.tsx, client/src/app/components/svgs/SoundLowSvg.tsx, client/src/app/components/svgs/SoundMutedSvg.tsx, client/src/app/features/live/Live.tsx, client/src/app/features/live/LiveSection.tsx, client/src/app/features/live/NoLiveContent.tsx, client/src/app/features/live/VideoIconButton.tsx
<br><br>
- `NoLiveContent` UI 리팩토링
- `LiveInfo` 개발 및 팔로우 버튼 리팩토링
- 비디오 컨트롤러 래퍼 작성 및 호버링 기능 추가
- 관련 SVG 컴포넌트 작성
=> feat: NoLiveContent, LiveInfo, 비디오 컨트롤러 래퍼 형태 및 관련 SVG 컴포넌트

client/src/app/features/live/Live.tsx, client/src/app/features/live/LiveSection.tsx
<br><br>
- togglePip 함수를 통해 pipButton을 isPip 상태값에 따라 다르게 렌더링
=> feat: PipButton UI

client/src/app/components/svgs/FullscreenQuitSvg.tsx, client/src/app/components/svgs/FullscreenSvg.tsx, client/src/app/features/live/Live.tsx, client/src/app/features/live/LiveSection.tsx, client/src/app/features/live/VideoIconButton.tsx, client/tailwind.config.ts
<br><br>
- fullscreen UI 및 로직 작성 중입니다.
=> feat: fullscreen 버튼 UI 작업 중

aplicationServer/src/types.ts
<br><br>
Application Server의 응답 Type을 정의하였다.
=> API 서버 응답 Type 정의

client/src/app/components/layout/HeaderControlButton.tsx, client/src/app/components/studio/StudioHeader.tsx, client/src/app/components/studio/StudioLogo.tsx, client/src/app/components/studio/StudioRouter.tsx, client/src/app/studio/layout.tsx, client/src/app/studio/my/page.tsx
<br><br>
- 메인 페이지의 스튜디오 버튼을 통해 스튜디오로 진입 
- 방송 설정 페이지, 내 방송 페이지로 이동 가능
- 로그아웃 버튼을 통해 로그인 페이지로 이동 가능
- 로고 클릭시 메인 페이지로 이동 가능
=> feat: 스튜디오 헤더

client/src/app/components/studio/StudioImageInput.tsx, client/src/app/studio/features/my/MyStudioChat.tsx, client/src/app/studio/features/my/MyStudioInfo.tsx, client/src/app/studio/my/page.tsx
<br><br>
- 공통 컴포넌트를 조합하여 페이지 UI 작성
- 컴포넌트화 필요
=> feat: MyStudioPage

applicationServer/src/live/live.controller.ts, applicationServer/src/live/live.service.ts, applicationServer/src/types.ts, applicationServer/test/live/live.service.spec.ts, mediaServer/core/rtmp/stream.ts
<br><br>
기존 특정 방송에 접근하면 요청하는 API의 반환 값을 playlist url만 반환하던 상태에서 playlis url과 방송 정보를 함께 전달하도록 변경하였습니다.
=> PlaylistUrl 반환 API 반환 값 변경

applicationServer/src/constants.ts, applicationServer/src/live/live.controller.ts, applicationServer/src/live/live.service.ts
<br><br>
- SSE 연결 요청에 따라 연결을 수립한다.
- 주기적으로 방송 정보를 전달한다.
- SSE 연결 소켓에 따라 시청자 수를 증감시킨다.
=> Application Server SSE 연결 및 전달 API 구현

applicationServer/src/auth/github/github.controller.ts
<br><br>
- code를 body로 받도록 변경하였다.
- 응답값에 이름과 방송 아이디를 추가하였다.
=> Github Callback URL 요청/응답 형식 및 값 변경

chatServer/main.ts
<br><br>
- cors origin에 https://www.funch.site를 추가하여 해결하였다.
- generateRandomName 모듈의 상대 경로를 명확히 해주었다.
=> cors 오류 해결

client/src/app/components/cabinet/Cabinet.tsx, client/src/app/components/cabinet/CabinetContainer.tsx, client/src/app/components/cabinet/DesktopHeader.tsx, client/src/app/components/cabinet/FollowList.tsx, client/src/app/components/cabinet/SuggestedList.tsx, client/src/libs/internalTypes.ts
<br><br>
- Link 적용
- title (absolute -> fixed)
=> feat: 추천 스트리머 목록

client/configs/tailwind.constant.ts, client/package-lock.json, client/package.json, client/src/__mocks__/chats.ts, client/src/app/(domain)/features/live/Chat.tsx, client/src/app/(domain)/features/live/LiveSection.tsx, client/src/app/providers/LiveProvider.tsx, client/src/hooks/useUser.ts, client/src/libs/constants.ts, client/src/libs/internalTypes.ts, client/tailwind.config.ts
- socket.io-client
- chat wrapper
- chat form
- chat list (demo)
=> feat: 채팅 UI 및 웹소켓 통신 로직 (1)

applicationServer/src/live/live.service.ts, applicationServer/src/live/mock/register-mock.util.ts, chatServer/package.json
=> mock live 등록 함수 추가

applicationServer/src/constants.ts, applicationServer/src/live/mock/register-mock.util.ts, applicationServer/src/main.ts, chatServer/main.ts, mediaServer/package.json
- funch.site의 `www`와 `@` 모두 origin에 추가하였다.
=> API 서버/채팅 서버 CORS 수정

chatServer/main.ts, client/next.config.mjs, client/src/app/(domain)/features/live/Chat.tsx
<br><br>
- 채팅창 채팅 목록 UI 중 '님' 제거
- 이미지 remotePattern에 avatars.githubusercontent.com을 추가
=> fix: 채팅 아이템 '님' 빼기, 이미지 패턴 추가(넥스트 프록시)

chatServer/main.ts, client/next.config.mjs, client/src/__mocks__/mydata.ts, client/src/app/(domain)/features/live/Chat.tsx, client/src/app/components/svgs/PrismSvg.tsx, client/src/app/studio/features/StreamSettingContainer.tsx, client/src/app/studio/features/StudioCopyButton.tsx, client/src/app/studio/features/StudioGuideContainer.tsx, client/src/app/studio/features/StudioInfoSettingGuide.tsx, client/src/app/studio/features/StudioReIssueButton.tsx, client/src/app/studio/page.tsx, client/src/libs/actions.ts, client/src/libs/internalTypes.ts, client/src/server/handlers.ts
<br><br>
- stroke-width -> strokeWidth
- px -> rem으로 단위 변경
- mydata 타입 추가
- msw, actions에 핸들러 추가
- 재발급 버튼 추가(로직 미구현)
- 재발급 버튼 누를시 나올 모달도 구현해야함
=> 방송 설정 페이지 API 연결, 간단한 수정

client/src/app/(domain)/categories/contents/[code]/page.tsx, client/src/app/(domain)/categories/features/CategoryCard.tsx, client/src/app/(domain)/categories/features/ContentsCategoryImage.tsx, client/src/app/(domain)/categories/features/MoodsCategoryPalette.tsx, client/src/app/(domain)/categories/moods/[code]/page.tsx, client/src/app/(domain)/categories/page.tsx, client/src/assets/categories/communication.svg, client/src/libs/constants.ts, client/src/libs/data.ts, client/src/libs/internalTypes.ts
<br><br>
- 콘텐츠 카테고리 상수 예시 생성
- 콘텐츠 카테고리 목록 노출
- 각 이미지 클릭 시 해당 카테고리 상세 페이지로 라우팅
- 분위기 카테고리 목록 노출
- 분위기 카테고리 아이템 클릭 시 해당 카테고리 페이지로 라우팅
- 카테고리 constants 키 이름 컨벤션 맞추기
=> feat: 카테고리 페이지

client/src/app/components/studio/StudioCategoryCard.tsx, client/src/app/components/studio/StudioDropdown.tsx, client/src/app/studio/my/features/MyStudioForm.tsx, client/src/server/handlers.ts
<br><br>
- 카테고리, 무드 연결
- StudioCategoryCard UI
=> feat: 스튜디오 드롭다운

client/package-lock.json, client/package.json, client/src/app/TanstackInitializer.tsx, client/src/app/components/ErrorBoundary.tsx, client/src/app/components/livesGrid/Lives.tsx, client/src/app/layout.tsx, client/src/app/providers/LiveProvider.tsx
=> refactor: LiveSection

client/package-lock.json, client/package.json, client/src/__mocks__/broadcasts.ts, client/src/__test__/actions.test.ts, client/src/app/(auth)/features/AuthLoading.tsx, client/src/app/(auth)/github/callback/features/AuthGithub.tsx, client/src/app/(auth)/google/callback/features/AuthGoogle.tsx, client/src/app/(auth)/naver/callback/features/AuthNaver.tsx, client/src/app/(domain)/categories/(details)/contents/[code]/page.tsx, client/src/app/(domain)/categories/(details)/moods/[code]/page.tsx, client/src/app/(domain)/features/RecommendedLives.tsx, client/src/app/(domain)/features/RecommendedLivesRenderer.tsx, client/src/app/(domain)/features/live/Chat.tsx, client/src/app/(domain)/features/live/Live.tsx, client/src/app/(domain)/features/live/LiveInfo.tsx, client/src/app/(domain)/features/live/LiveSection.tsx, client/src/app/(domain)/features/live/MiniPlayerController.tsx, client/src/app/(domain)/features/live/VideoController.tsx, client/src/app/components/Button.tsx, client/src/app/components/ErrorBoundary.tsx, client/src/app/components/layout/Search.tsx, client/src/app/components/livesGrid/Lives.tsx, client/src/app/global-error.tsx, client/src/app/not-found.tsx, client/src/app/providers/LiveProvider.tsx, client/src/hooks/useHls.ts, client/src/libs/constants.ts, client/tailwind.config.ts
- 다른 방송 화면 이동 시 채팅 초기화하기
- chat 소켓 연결 에러 핸들링
- 라이브 프로바이더 개선 진행
- 방송 전체 및 채팅 에러/로딩 처리 개선
- AuthLoading
- HLS 에러, 로딩, 버퍼링 이벤트 핸들러 추가
- 비디오 버퍼링 배경색 조절 및 sharp 설치
- 채팅 맨 위에 메세지 노출
- reconnect 시 error 등 초기화하도록
- error 소켓 이벤트도 constants로 관리
- 미니 플레이어 상단 버튼 테두리
- 홈 추천 라이브 목록을 서버 컴포넌트로 리팩토링
- not-found.tsx
- global-error.tsx
=> 라이브 및 채팅 개선, not-found, global-error 작성

client/src/app/(domain)/features/live/LiveInfo.tsx
- eventSource.onerror 시 close()만 하도록 수정
- data가 존재하는 경우에만 refreshInfo 하도록 eventSource.onmessage 수정
=> LiveInfo EventSource onmessage 및 onerror 로직 수정

client/plugins/tailwind.plugin.ts, client/src/app/(domain)/features/FollowingLives.tsx, client/src/app/(domain)/following/features/Follow.tsx, client/src/app/(domain)/page.tsx, client/src/app/components/cabinet/CabinetContainer.tsx, client/src/app/components/cabinet/CabinetItemList.tsx, client/src/app/components/cabinet/CabinetLink.tsx, client/src/app/components/cabinet/DesktopHeader.tsx, client/src/app/studio/features/StreamSettingContainer.tsx, client/src/app/studio/features/StudioCopyButton.tsx, client/src/app/studio/my/features/MyStudioForm.tsx
<br><br>
- isError를 검사하기 전 isLoggedin 여부를 검사하도록 수정
- 위에서 props를 받아서 childNode에서 복사와 토스트 띄우기를 한번에 하는 형태로 변경
=> fix: 복사 기능, 비로그인시 isError 이슈

client/src/__mocks__/broadcasts.ts, client/src/app/providers/UserProvider.tsx, client/src/app/studio/my/features/MyStudioChat.tsx, client/src/app/studio/my/features/MyStudioVideo.tsx, client/src/app/studio/my/features/StudioChatDemo.tsx, client/src/app/studio/my/page.tsx, client/src/hooks/useUser.ts
=> feat: 스튜디오 비디오 영역 및 채팅 영역

.github/workflows/deployment.yml, .github/workflows/integration.yml, .gitignore, applicationServer/src/auth/core/auth.service.ts
<br><br>
CI를 위한 .github/workflows/integration.yml 파일과
CD를 위한 .github/workflows/deployment.yml 파일을 추가했습니다.
=> Github Actions workflow 추가

client/src/app/(auth)/github/callback/features/AuthGithub.tsx, client/src/app/(auth)/google/callback/features/AuthGoogle.tsx, client/src/app/(auth)/naver/callback/features/AuthNaver.tsx, client/src/app/auth/features/Auth.tsx, client/src/app/providers/UserProvider.tsx, client/src/libs/fetcher.ts
-  fetcher 내 access-token 로직 수정
- isValidCall로 가드
- 로그아웃 시 리프레시, 리프레시토큰 제거
=> 로그아웃 시 리프레시 및 로그인 API 한 번만 호출하기 시도

.github/workflows/deployment.yml, chatServer/main.ts, mediaServer/main.ts
<br><br>
Github Actions를 이용해 CD를 하는 과정에서 workflow의 run 스크립트에서 환경 변수를 잘못 사용하던 부분을 변경하였습니다.
=> Github Actions 배포 workflow 수정

client/src/app/(domain)/features/RecommendedLives.tsx, client/src/app/(domain)/features/live/LiveInfo.tsx, client/src/app/(domain)/features/live/LiveSection.tsx
<br><br>
- SSE 연결 유지를 위해 LiveInfo style 변경
- recommendlives에서 no-cache 옵션 제거
=> LiveInfo 언마운트 되지 않도록 수정

client/src/__mocks__/follow.ts, client/src/app/(domain)/features/RecommendedLivesRenderer.tsx, client/src/app/components/cabinet/CabinetContainer.tsx, client/src/app/components/studio/StudioImageInput.tsx, client/src/app/components/studio/StudioUpdateButton.tsx, client/src/app/providers/FollowingLivesProvider.tsx, client/src/app/studio/my/features/MyStudioForm.tsx
<br><br>
- 필터링은 useMemo로 팔로우 목록 ids, 추천 리스트를 의존성 배열에 담아 memo 해줌
=> refactor: 내 방송 미리보기 이미지 추가, 팔로우 목록을 추천 목록에서 필터링

applicationServer/test/follow/follow.controller.spec.ts
<br><br>
- follow API가 수정됨에 따라 테스트 코드도 수정하였다.
=> Follow Test 코드 수정

client/src/app/studio/features/StreamSettingContainer.tsx, client/src/libs/actions.ts, client/src/server/handlers.ts
<br><br>
- 재발급이 알럿이 뜨도록 함. 토스트로 처리할 까 했으나 재발급 이후 복사가 되는것은 아니기 때문에 알럿으로 처리했음.
- 추후 모달을 통해 재발급 할건지 재차 확인하는 로직이 있다면 좋을 것 같음
=> feat: 스트림 키 재발급 기능

client/src/app/(domain)/features/live/Chat.tsx, client/src/app/components/Button.tsx, client/src/app/studio/my/features/StudioChat.tsx, client/src/libs/data.ts, client/src/libs/internalTypes.ts
<br><br>
- 라이브 섹션 내 sendChat 로직 수정 및 dropdown 구현
- 내 방송 페이지에도 번역 드롭다운 적용 및 관련 리팩토링
=> feat: 번역 모드 설정을 위한 채팅 내 UI 및 로직

applicationServer/package-lock.json, applicationServer/package.json, applicationServer/src/auth/core/auth.controller.ts, applicationServer/src/auth/core/auth.guard.ts, applicationServer/src/auth/core/auth.module.ts, applicationServer/src/auth/core/auth.service.ts, applicationServer/src/auth/github/github.controller.ts, applicationServer/src/auth/google/google.controller.ts, applicationServer/src/auth/naver/naver.controller.ts, applicationServer/src/constants.ts, applicationServer/src/database/redis.service.ts, applicationServer/test/auth/core/auth.guard.spec.ts, applicationServer/test/auth/core/auth.service.spec.ts, deploy/funch-deploy.sh
<br><br>
- RedisService에서 redis에 토큰 저장/삭제/조회 기능을 담당하도록 분리하였다.
=> Redis에 토큰 저장

client/src/app/components/studio/StudioMoodDropdown.tsx, client/src/app/studio/my/features/MyStudioForm.tsx
=> refactor: MyStudioForm 리팩토링

client/src/app/components/cabinet/CabinetItemList.tsx, client/src/app/components/studio/StudioCategoryDropdown.tsx, client/src/app/components/studio/StudioMoodDropdown.tsx, client/src/app/components/studio/StudioTextarea.tsx, client/src/app/components/studio/StudioUpdateButton.tsx, client/src/app/components/studio/TextareaRenderer.tsx, client/src/app/studio/my/features/MyStudioForm.tsx
<br><br>
- 방송 제목이 최소 1자는 되어야함(안그럼 업데이트 막음)
- 제목이 1자도 안되는데 textarea에 포커싱됐을때 경고문구 출력
- 카테고리 드롭다운 불필요한 상태 변수 제거
- 서랍 title 크기 없앰
=> refactor: StudioTextarea

client/src/app/(domain)/search/feature/SearchContainer.tsx, client/src/app/components/studio/StudioMoodDropdown.tsx
<br><br>
- useEffect 의존성에 쿼리스트링 추가
- 불필요한 console.log 제거
=> refactor: 검색 결과에 따른 컴포넌트 렌더링

chatServer/utils/translation.ts
- 채팅에 번역이 안되는 문장이 있을 경우 원래 문자열이 반환된다.
=> 채팅 번역이 안되는 경우 처리

chatServer/utils/translation.ts
- translationMap의 value안에서 찾는 것으로 수정하였다.
=> 채팅 번역 기능 수정

.github/workflows/deployment.yml, applicationServer/src/constants.ts, applicationServer/src/database/redis.service.ts, applicationServer/src/live/live.controller.ts, applicationServer/src/live/live.service.ts, applicationServer/test/live/live.service.spec.ts
- ApplicationServer의 Live Test 코드를 Redis로 마이그레이션 된 상태로 수정하였습니다.
- 기존 Github Actions CD Workflow가 SSH 접속이 안되던 현상을 수정하였습니다.
- SSE 로직을 일부 수정했습니다.
=> Github Actions Deploy Workflow 및 테스트 코드 수정
