- mediaServer/core/rtmp/connect.ts
- mediaServer/core/rtmp/handshake.ts
- mediaServer/core/rtmp/packet.ts
- mediaServer/core/rtmp/stream.ts
- mediaServer/core/rtmp/utils.ts
- mediaServer/main.ts
- mediaServer/package-lock.json
- mediaServer/package.json
- mediaServer/test/core/rtmp.test.ts
- mediaServer/tsconfig.json
<br><br>
* AMF 형식을 결정하여 페이로드 디코딩
* 메시지 헤더의 typeId에 따라 AMF0/AMF3 형식을 결정하고 이에 맞게 페이로드를 디코딩하였다.
* Client로부터 오는 요청을 패킷 단위로 분리하여 객체로 생성
* 하나의 패킷에 여러 `chunk`가 올 경우를 생각하여 패킷을 `chunk` 단위로 분리하여 `chunk` 배열로 반환하도록 처리하였다.
* chunk` 단위 분리 로직은 [공식 문서](https://rtmp.veriskope.com/docs/spec/#531chunk-format)를 참고하여 형식에 맞게 분리하는 함수를 각각 작성하였다.
* RTMP Connect 과정을 모듈로 분리
* `Window Acknowledgement Size` 제어 메시지 전송
* `Set Peer Bandwidth` 제어 메시지 전송
* `Set Chunk Size` 제어 메시지 전송
* Result Command Response 메시지 전송
> RTMP Connect 수행

- client/src/app/categories/page.tsx
- client/src/app/components/cabinet/Cabinet.tsx
- client/src/app/components/cabinet/CabinetContainer.tsx
- client/src/app/components/cabinet/CabinetLink.tsx
- client/src/app/components/cabinet/CategoryLink.tsx
- client/src/app/components/cabinet/FollowLink.tsx
- client/src/app/components/cabinet/StreamerLink.tsx
- client/src/app/components/svgs/CategorySvg.tsx
- client/src/app/components/svgs/FollowSvg.tsx
- client/src/app/layout.tsx
- client/src/app/page.tsx
<br><br>
- 서랍은 categoryNavigator, streamerNavigator로 나뉘어 있음
- CabinetLink를 props에 따라 다른 라우트, 아이콘을 보이게 함
> feat: 서랍 상단 UI 구현

- client/next.config.mjs
- client/src/app/components/layout/Header.tsx
- client/src/app/components/layout/HeaderControlButton.tsx
- client/src/app/components/layout/StudioBtn.tsx
- client/src/app/components/layout/ThemeController.tsx
- client/src/app/components/layout/ToolBar.tsx
- client/src/app/components/livesGrid/Lives.tsx
- client/src/app/components/svgs/FunchSvg.tsx
- client/src/app/components/svgs/MoonSvg.tsx
- client/src/app/components/svgs/StudioSvg.tsx
- client/src/app/globals.css
- client/src/app/hooks/useInternalRouter.ts
- client/src/app/studio/page.tsx
- client/tailwind.config.ts
<br><br>
- header 내 컨트롤 버튼들을 HeaderControlButton 컴포넌트로 통합
- Image 컴포넌트 사용
- brand 색상이 violet 사용하도록 변경
- useInternalRouter hook
> refactor: HeaderControlButton, Image(for test), brand 색상, useInternalRouter

- client/configs/tailwind.constant.ts
- client/next.config.mjs
- client/src/app/components/layout/SearchView.tsx
- client/src/app/components/livesGrid/LiveBadge.tsx
- client/src/app/components/livesGrid/Lives.tsx
- client/tailwind.config.ts
- client/tsconfig.json
- client/vitest.config.ts
<br><br>
- 라이브 목록 요소의 높이도 화면 사이즈에 따라 변화하도록 테일윈드 설정 추가 및 코드 수정
- 컨벤션에 맞게 테일윈드 변수명 일부 변경
- 검색창 너비에 대한 변수를 설정하고 화면 너비에 따라 달리 사용
- deprecated인 domains 옵션을 사용하지 않고, RemotePatterns 사용 (next.config)
> feat: 라이브 목록 아이템의 반응형 높이, 검색창 반응형 너비

- client/package-lock.json
- client/package.json
- client/src/app/GlobalProvider.tsx
- client/src/app/components/cabinet/FollowList.tsx
- client/src/app/components/svgs/NotifySvg.tsx
- client/src/app/features/live/Live.tsx
- client/src/app/features/live/LiveSection.tsx
- client/src/app/features/live/NoLiveContent.tsx
- client/src/app/hooks/useLiveContext.ts
- client/src/app/layout.tsx
- client/src/app/lives/[id]/page.tsx
- client/src/app/providers/LiveProvider.tsx
- client/src/app/providers/UserProvider.tsx
<br><br>
- 라이브 섹션 및 라이브 프로바이더 프로토타입 작성
- play, pause, fullscreen, pip, volume control의 프로토타입 작성
- 서랍 UI 리팩토링
- 비디오를 렌더링 하기 위한 라이브 섹션 및 라이브 컴포넌트의 프로토타입을 작성 계속 진행
> feat: 라이브 섹션 및 라이브 프로바이더, 컨트롤러 기능 등 프로토타입 작성 진행

- client/configs/tailwind.constant.ts
- client/next.config.mjs
- client/plugins/tailwind.plugin.ts
- client/src/app/__mocks__/lives.ts
- client/src/app/components/cabinet/Cabinet.tsx
- client/src/app/components/cabinet/FollowList.tsx
- client/src/app/components/layout/ToolBar.tsx
- client/src/app/components/livesGrid/LiveBadge.tsx
- client/src/app/components/svgs/ChatFoldSvg.tsx
- client/src/app/components/svgs/DottedSvg.tsx
- client/src/app/features/Badge.tsx
- client/src/app/features/live/Live.tsx
- client/src/app/features/live/LiveSection.tsx
- client/src/app/layout.tsx
- client/src/app/libs/constants.ts
- client/src/app/libs/formats.ts
- client/src/app/providers/LiveProvider.tsx
- client/src/app/providers/ThemeProvider.tsx
- client/tailwind.config.ts
<br><br>
- 테마 설정 시 로컬 스토리지에도 저장하도록 기능 추가
- 채팅 색상을 테마를 사용하지 않고 변수를 사용하도록 수정
- video, videoControllersWrapper peer로 지정
- LiveInfo의 UI를 작성
- 채팅 영역을 고려하여 레이아웃 및 채팅 영역 프로토타입을 작성하였다.
- 관련한 기타 테일윈드 설정을 추가했다.
- hls url -> live id로 변경
- live section 시나리오 작성
> feat: 방송 섹션

- client/src/app/features/live/Live.tsx
- client/src/app/features/live/LiveSection.tsx
- client/src/app/features/live/VideoController.tsx
- client/src/app/hooks/useMouseMovementOnElement.ts
- client/src/app/hooks/usePip.ts
- client/src/app/hooks/usePlay.ts
- client/src/app/hooks/useThemeContext.ts
- client/src/app/libs/constants.ts
- client/src/app/libs/internalTypes.ts
- client/src/app/providers/ThemeProvider.tsx
<br><br>
- 라이브 섹션 레이아웃 구체화 및 분리
- 컨트롤러 버튼 ARIA 및 title 속성 추가
- 타입 선언 분리 및 컨벤션 맞추기
- 웹에서 제공하는 pip 종료 버튼을 핸들링하기 위해 enterpictureinpicture, leavepictureinpicture 이벤트를 핸들링하는 이팩트를 usePip에 추가
- 비디오 컨트롤러 부분을 라이브 파일로부터 분리했다.
> refactor: 라이브 섹션 및 라이브 영역 컴포넌트 리팩토링, pip 핸들러 개선

- client/next.config.mjs
- client/src/__mocks__/broadcasts.ts
- client/src/__mocks__/users.ts
- client/src/__test__/msw.test.ts
- client/src/__test__/sum.test.ts
- client/src/app/(domain)/features/RecommendedLives.tsx
- client/src/app/components/livesGrid/Lives.tsx
- client/src/libs/internalTypes.ts
- client/src/server/handlers.ts
- client/vitest.setup.ts
- `/api/:path*`에 대한 요청을 production인 경우 `https://api.example.com/:path\*`로 rewrite하도록 next.config.mjs 임시 수정
- Broadcast, Playlist, Streamkey, Token, User 타입 선언 (internalTypes.ts)
- broadcast, user에 대한 목 데이터 생성 (mockedBroadcasts, mockedUsers)
- msw 핸들러 추가 (getBroadcasts, getUserByBroadcastId)
- msw 핸들러 테스트 코드 추가
> chore: 서버 타입(v0.1.0) 반영 및 msw 테스트 일부 작성

- applicationServer/package-lock.json
- applicationServer/package.json
- applicationServer/src/app.module.ts
- applicationServer/src/live/entities/live.entity.ts
- applicationServer/src/live/live.controller.ts
- applicationServer/src/live/live.module.ts
- applicationServer/src/live/live.service.ts
- applicationServer/test/live/live.service.spec.ts
- applicationServer/tsconfig.json
<br><br>
- Application Server에서 방송 정보를 전역적으로 메모리에서 관리하기 위해 Live Entity를 생성했습니다.
- 특정 broadcastId를 `live/:broadcastId`로 전달 시 생방송 중인지 확인해 결과 값을 달리 반환하는 모듈을 작성하였습니다.
- service 로직에 대한 테스트 코드를 `application/test` 디렉토리에 작성했습니다.
> 클라이언트 live playlist 요청에 따른 응답 API 구현

- applicationServer/src/live/entities/live.entity.ts
- applicationServer/src/live/live.controller.ts
- applicationServer/src/live/live.module.ts
- applicationServer/src/live/live.service.ts
- applicationServer/src/member/member.entity.ts
- applicationServer/src/member/member.service.ts
- applicationServer/src/utils/interceptor/live.interceptor.ts
- applicationServer/test/live/live.service.spec.ts
<br><br>
- 단일 멤버 반환 함수 작성
- 기존 방송 정보만 반환하던 API를 방송 정보와 스트리머 정보를 함께 반환하도록 수정
- 위 사유로 반복 코드 인터셉터로 분리
- 함수 리네이밍
> 추천, 전체 방송 정보 반환 함수 변경

- applicationServer/src/live/live.controller.ts
- applicationServer/src/live/live.service.ts
- applicationServer/src/types.ts
- mediaServer/core/fetch.ts
- mediaServer/core/media/ffmpeg.ts
- mediaServer/core/rtmp/stream.ts
- mediaServer/core/rtmp/utils.ts
- 방송 파일 경로가 기존 broadcast 이름으로 만들어진 디렉토리에서 내부 추가
디렉토리 경로가 생김에 따라 broadcast properties에 broadcastPath를
추가하였습니다.
- CPU 사용량을 줄이기 위해 FFMpeg으로 m4v 파일을 만드는 과정에서 480p 생성
코드를 제거하였습니다.
- 기존 중복된 코드였던 startStreaming과 endStreaming을 streamingEvent 함수
하나로 변경하였고, 전달받는 인자값을 streamKey와 internalPath를 함께
받을 수 있도록 객체 형태로 전달받도록 변경하였습니다.
- this.storagePath가 정해지기 전 종료 관련 이벤트가 발생했을 때
storagePath가 undefined으로 처리되는 현상을 막기 위한 소켓 이벤트 분리와
방송 종료 시 방송 디렉토리를 제거하던 로직을 삭제하고, 방송 별 디렉토리
분리로 변경함에 따라 internalPath를 방송 시작 시 함께 전달하도록
변경하였습니다.
> 안정적인 미디어 서버를 위한 리팩토링

- applicationServer/src/app.module.ts
- applicationServer/src/constants.ts
- applicationServer/src/database/database.providers.ts
- applicationServer/src/follow/follow.controller.ts
- applicationServer/src/follow/follow.entity.ts
- applicationServer/src/follow/follow.module.ts
- applicationServer/src/follow/follow.providers.ts
- applicationServer/src/follow/follow.service.ts
- applicationServer/src/member/member.providers.ts
- applicationServer/tsconfig.json
<br><br>
* DataSource 주입 방식을 문자열 토큰 방식이 아닌 클래스 참조를 사용하도록 변경
* 멤버 팔로우/언팔로우 기능 구현
* 로그인한 멤버가 아니라면 접근이 불가능하다. (401 Error)
* 만약 팔로우를 이미 한 상태에서 팔로우 요청을 하면 BAD_REQUEST 오류를 발생시킨다. (400 Error)
* 만약 팔로우를 하지 않은 상태에서 언팔로우 요청을 하면 BAD_REQUEST 오류를 발생시킨다. (400 Error)
* 본인 팔로우/언팔로우 금지 기능 추가
* 사용자의 팔로워/팔로잉 목록 가져오는 API 구현
> 스트리머 팔로우/언팔로우

- applicationServer/package.json
- applicationServer/src/app.module.ts
- applicationServer/src/auth/github/github.service.ts
- applicationServer/src/auth/naver/naver.controller.ts
- applicationServer/src/auth/naver/naver.module.ts
- applicationServer/src/auth/naver/naver.service.ts
- applicationServer/src/constants.ts
- applicationServer/src/live/mock/register-mock.util.ts
- applicationServer/test/auth/github/github.service.spec.ts
- applicationServer/tsconfig.json
<br><br>
- 네이버 로그인 API를 이용한 회원가입 및 로그인 로직을 구현하였습니다.
https://www.notion.so/zzawang/Naver-56dc615ab5fe4048b994196956b77d5c
- github 로그인 service 로직에 axios시 2xx 응답이 돌아오지 않아 프로세스가
종료되는 것을 방지하기 위해 catch로 에러를 처리할 수 있는 로직을
추가했습니다. 추가로 getUserInfo의 authorization header의 token type을
Token -> Bearer로 변경하였습니다.
- Github 로그인 시 사용하던 상수의 이름을 naver 로그인 추가에 따라
보편적인 이름에서 로그인 사이트를 특정할 수 있도록 변경하였습니다.
ex) RESOURCE_URL -> GITHUB_RESOURCE_URL
> 네이버 로그인/회원가입 기능 구현

- client/next.config.mjs
- client/src/app/(domain)/categories/features/ContentsCategoryImage.tsx
- client/src/app/(domain)/categories/features/MoodsCategoryPalette.tsx
- client/src/app/(domain)/features/live/Chat.tsx
- client/src/app/(domain)/features/live/Live.tsx
- client/src/app/(domain)/features/live/LiveInfo.tsx
- client/src/app/(domain)/features/live/LiveSection.tsx
- client/src/app/providers/LiveProvider.tsx
<br><br>
- savedId 상태를 LiveProvider에 추가하고 이팩트에 비교 조건문을 추가
- LiveInfo 컴포넌트에 SSE 통신 이팩트 추가
- LiveInfo 각 요소 메모이제이션
- 채팅 컴포넌트 소켓 통신 데이터 타입에 컬러 추가
- production에서 콘솔 로그 미노출
> feat: 라이브 프로바이더 개선, SSE 통신

- applicationServer/package.json
- applicationServer/src/constants.ts
- applicationServer/src/follow/follow.controller.ts
- applicationServer/test/app.e2e-spec.ts
- applicationServer/test/follow/follow.controller.spec.ts
<br><br>
* 팔로워 매핑 key 수정
*  상수화 과정 중 팔로워 리스트를 추출하는 키에 S를 추가하여 FOLLOWER가 아닌 FOLLOWERS로 등록했었다. 테스트 과정 중 해당 버그를 발견하게 되어 FOLLOWERS -> FOLLOWER로 수정 후 정상적으로 추출하도록 변경하였다.
* follow 기능 테스트 코드 추가
> Follow API 테스트 코드 추가 및 버그 수정

- applicationServer/src/live/live.controller.ts
- applicationServer/src/live/live.service.ts
- applicationServer/src/member/member.service.ts
- applicationServer/src/types.ts
<br><br>
- 팔로잉된 스트리머를 기준으로 방송 중이라면 방송 정보를, 아니라면
스트리머 정보를 반환하는 API를 구현하였습니다.
- 멤버 데이터를 팔로잉 기준으로 가져올 수 있도록 테이블을 조인해 반환하는
쿼리 함수를 작성하였습니다.
- User 타입을 클라이언트에서 일관성있게 사용할 수 있도록 기존 MyData를 반환하는 형태로 속성 이름을 변경하였고, 팔로잉 방송 목록을 반환할 때 온라인은 방송 정보를, 오프라인은 스트리머 정보를 반환하기 때문에 isLive 속성은 제거하였습니다.
> 팔로우 방송 목록 반환 API 구현

- client/configs/tailwind.constant.ts
- client/src/app/(domain)/features/live/Chat.tsx
- client/src/app/(domain)/features/live/LiveSection.tsx
- client/src/app/providers/LiveProvider.tsx
- client/src/hooks/useUser.ts
<br><br>
- 채팅 폼과 채팅 아이템 간 간격 조절 (채팅 전체 레이아웃 개선) #280
- 새로운 채팅 존재 시 자동 스크롤 되도록
- 각 채팅 아이템 메모이제이션
- 화면 이동 후 재방문 시 채팅 유지되도록 관련 로직 수정
> feat: 채팅 개선

- deploy/funch-blue-ecosystem.config.json
- deploy/funch-deploy.sh
- deploy/funch-green-ecosystem.config.json
- deploy/media-deploy.sh
- deploy/media-ecosystem.config.json
<br><br>
- Blue/Green deployment 전략을 사용하기 위해 각 Blue/Green상태의 포트에 맞는 서버 프로세스를 띄운다.
- 새로운 코드가 반영된 서버가 실행되면 Nginx proxy_pass 설정에서 해당 서버에 맞는 포트로 설정해준다.
> 무중단 배포를 위한 ecosystem.config.json과 쉘 스크립트 파일 작성

- client/plugins/tailwind.plugin.ts
- client/src/app/components/layout/Search.tsx
- client/src/app/components/layout/SearchView.tsx
- client/src/hooks/useClickOutside.ts
- client/src/hooks/useHls.ts
- client/src/libs/constants.ts
<br><br>
- isCurrentlyWaitingRef를 추가해 버퍼링 타임아웃이 중복되지 않도록 함
- NoPrevSearch UI
- isCurrentlyWaitingRef 사용 로직을 bufferingTimeoutRef로 통합 적용
- 검색창 세부 UI 및 지난 검색어 활용, onChange 핸들러 등
> useHls 개선 및 검색창 구현

- client/src/__mocks__/result.ts
- client/src/app/(domain)/following/features/FollowingOffair.tsx
- client/src/app/(domain)/search/feature/SearchContainer.tsx
<br><br>
- queryParams를 통해 액션 함수 작동
- lives, members를 받아 lives가 없는 경우에만 오프라인을 렌더링하도록 함
> feat: Search 페이지

- applicationServer/test/follow/follow.controller.spec.ts
- applicationServer/test/live/live.service.spec.ts
<br><br>
- 로컬에서는 `.env`에 DB 정보가 들어가있었기 때문에 테스트가 원할하게 되었지만 Github에서는 정보가 없기 때문에 테스트가 실패한 것이었다. 따라서 이를 해결하기 위해 MemberService를 모킹하여 주입하였다.
> CI에서 테스트 실패 해결

- client/src/app/(domain)/features/RecommendedLives.tsx
- client/src/app/(domain)/features/live/LiveInfo.tsx
- client/src/app/(domain)/page.tsx
- client/src/app/TanstackInitializer.tsx
- client/src/app/components/cabinet/CabinetItemList.tsx
- client/src/app/components/cabinet/DesktopHeader.tsx
- client/src/app/components/layout/SearchView.tsx
- client/src/libs/actions.ts
- client/src/libs/constants.ts
<br><br>
- 서랍의 리프레시 버튼, 펴기//접기 버튼 크기를 w-7, h-7으로 조정 (라이트하우스 권고)
- 서랍 일부 UI 텍스트 색상 개선 (라이트하우스 권고)
- RecommendedLives를 클라이언트 컴포넌트로 리팩토링
> 홈 라이브 리스트 클라이언트 컴포넌트로 리팩토링 및 tanstack-query + suspense 적용, 서랍 일부 UI 개선

- .github/workflows/deployment.yml
- chatServer/main.ts
- chatServer/utils/translation.ts
- mediaServer/core/media/ffmpeg.ts
<br><br>
- Github Actions의 Deployment workflow의 funch server deploy 스크립트에
client를 build한 이후 하위 디렉토리에 npm install을 수행해 의존성을 갱신하도록 변경하였습니다. 반영하도록 변경하였습니다.
- 클러스터링 도입을 테스트한 이후 특별한 효과를 보지 못해 FFMpeg의 Output
Options에 -threads 2 명시적으로 추가해주는 것으로 마무리 했습니다.
- Clova Studio API를 활용해 필요하다면 번역을 수행하는 기능을 채팅 서버에 포함했습니다.
> 채팅 번역 기능 추가

- client/src/app/studio/my/features/StudioVideo.tsx
- 내 방송 페이지 내 NoPlaylist 컴포넌트의 포지션 설정에 오류가 있어 수정함.
> hotfix: 스튜디오 페이지 NoPlaylist의 포지션 설정 오류 해결
